// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzOIO7qyOm5TN0j75eAbaHo0_ruFiiU_Y',
    appId: '1:60206258249:web:9c0a845c1a4550b92d0798',
    messagingSenderId: '60206258249',
    projectId: 'destiantionteller-dis-manage',
    authDomain: 'destiantionteller-dis-manage.firebaseapp.com',
    databaseURL: 'https://destiantionteller-dis-manage-default-rtdb.firebaseio.com',
    storageBucket: 'destiantionteller-dis-manage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9tGVOW_8LEbRDkH7DeWb8DQL5G6h0N9o',
    appId: '1:60206258249:android:9f1a88d79fcba76c2d0798',
    messagingSenderId: '60206258249',
    projectId: 'destiantionteller-dis-manage',
    databaseURL: 'https://destiantionteller-dis-manage-default-rtdb.firebaseio.com',
    storageBucket: 'destiantionteller-dis-manage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3bUxTR-pCOloE2-a3cZg8kKIEzhO8eyo',
    appId: '1:60206258249:ios:33220774ea2b4eed2d0798',
    messagingSenderId: '60206258249',
    projectId: 'destiantionteller-dis-manage',
    databaseURL: 'https://destiantionteller-dis-manage-default-rtdb.firebaseio.com',
    storageBucket: 'destiantionteller-dis-manage.firebasestorage.app',
    iosBundleId: 'com.example.disManag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3bUxTR-pCOloE2-a3cZg8kKIEzhO8eyo',
    appId: '1:60206258249:ios:33220774ea2b4eed2d0798',
    messagingSenderId: '60206258249',
    projectId: 'destiantionteller-dis-manage',
    databaseURL: 'https://destiantionteller-dis-manage-default-rtdb.firebaseio.com',
    storageBucket: 'destiantionteller-dis-manage.firebasestorage.app',
    iosBundleId: 'com.example.disManag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzOIO7qyOm5TN0j75eAbaHo0_ruFiiU_Y',
    appId: '1:60206258249:web:62b8c09e1fb73aae2d0798',
    messagingSenderId: '60206258249',
    projectId: 'destiantionteller-dis-manage',
    authDomain: 'destiantionteller-dis-manage.firebaseapp.com',
    databaseURL: 'https://destiantionteller-dis-manage-default-rtdb.firebaseio.com',
    storageBucket: 'destiantionteller-dis-manage.firebasestorage.app',
  );

}